export const initialCategories = [
  { _id: "cat_1", name: "Music & Concerts", slug: "music-concerts", description: "Live shows, music festivals, acoustic nights, and DJ sets.", isActive: true },
  { _id: "cat_2", name: "Tech & Innovation", slug: "tech-innovation", description: "Hackathons, AI summits, developer meetups, and keynote talks.", isActive: true },
  { _id: "cat_3", name: "Workshops & Masterclasses", slug: "workshops-masterclasses", description: "Hands-on learning, creative arts, business bootcamps, and coding workshops.", isActive: true },
  { _id: "cat_4", name: "Business & Networking", slug: "business-networking", description: "Startup pitch events, founder mixers, and investor panels.", isActive: true },
  { _id: "cat_5", name: "Sports & Wellness", slug: "sports-wellness", description: "Marathons, yoga retreats, esports tournaments, and fitness expos.", isActive: true },
];

export const initialEvents = [
  {
    _id: "evt_1",
    title: "Neon Horizon Cyberpunk Music Fest 2026",
    slug: "neon-horizon-cyberpunk-music-fest-2026",
    description: "Immerse yourself in a futuristic audio-visual extravaganza featuring top international electronic artists, neon light installations, and holographic stage design.",
    category: "cat_1",
    venue: "Cosmo Dome Arena",
    city: "Mumbai",
    startDate: "2026-08-15",
    endDate: "2026-08-16",
    startTime: "18:00",
    endTime: "02:00",
    ticketPrice: 2499,
    totalSeats: 1500,
    availableSeats: 420,
    bannerImage: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=1200&q=80",
    galleryImages: [
      "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=800&q=80"
    ],
    backgroundStyle: "aurora",
    featured: true,
    status: "published",
    createdBy: "usr_admin",
    isActive: true,
    createdAt: "2026-07-01T10:00:00Z"
  },
  {
    _id: "evt_2",
    title: "Global AI & Quantum Tech Summit 2026",
    slug: "global-ai-quantum-tech-summit-2026",
    description: "Join 2,000+ AI researchers, founders, and engineers exploring Generative AI models, Quantum Computing breakthroughs, and Autonomous Robotics.",
    category: "cat_2",
    venue: "Tech Next Convention Center",
    city: "Bengaluru",
    startDate: "2026-09-02",
    endDate: "2026-09-04",
    startTime: "09:00",
    endTime: "18:00",
    ticketPrice: 4999,
    totalSeats: 800,
    availableSeats: 95,
    bannerImage: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1200&q=80",
    galleryImages: [
      "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?auto=format&fit=crop&w=800&q=80"
    ],
    backgroundStyle: "grid",
    featured: true,
    status: "published",
    createdBy: "usr_admin",
    isActive: true,
    createdAt: "2026-07-05T12:00:00Z"
  },
  {
    _id: "evt_3",
    title: "Full-Stack Web3 & React Masterclass",
    slug: "full-stack-web3-react-masterclass",
    description: "An intensive 2-day hands-on workshop building decentralized applications, smart contract integrations, and high-performance React frontends.",
    category: "cat_3",
    venue: "Innovation Hub, Sector 62",
    city: "Noida",
    startDate: "2026-08-22",
    endDate: "2026-08-23",
    startTime: "10:00",
    endTime: "17:00",
    ticketPrice: 1499,
    totalSeats: 120,
    availableSeats: 18,
    bannerImage: "https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=1200&q=80",
    galleryImages: [],
    backgroundStyle: "particles",
    featured: false,
    status: "published",
    createdBy: "usr_admin",
    isActive: true,
    createdAt: "2026-07-10T15:30:00Z"
  },
  {
    _id: "evt_4",
    title: "Venture Wave Startup Mixer & Pitch Night",
    slug: "venture-wave-startup-mixer-pitch-night",
    description: "Connect directly with angel investors, VC firms, and fellow founders. Features a live pitch contest with $50k funding prizes.",
    category: "cat_4",
    venue: "Skyline Lounge & Club",
    city: "Delhi",
    startDate: "2026-08-28",
    endDate: "2026-08-28",
    startTime: "19:00",
    endTime: "23:00",
    ticketPrice: 999,
    totalSeats: 250,
    availableSeats: 64,
    bannerImage: "https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=80",
    galleryImages: [],
    backgroundStyle: "waves",
    featured: true,
    status: "published",
    createdBy: "usr_admin",
    isActive: true,
    createdAt: "2026-07-12T09:00:00Z"
  },
  {
    _id: "evt_5",
    title: "Sunset Beats Acoustic & Jazz Night",
    slug: "sunset-beats-acoustic-jazz-night",
    description: "Relax with soulful jazz improvisations, artisan cocktails, and waterfront views at sunrise-to-sunset rooftop live sessions.",
    category: "cat_1",
    venue: "Marine Waterfront Club",
    city: "Goa",
    startDate: "2026-09-10",
    endDate: "2026-09-10",
    startTime: "17:30",
    endTime: "22:30",
    ticketPrice: 1799,
    totalSeats: 300,
    availableSeats: 140,
    bannerImage: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1200&q=80",
    galleryImages: [],
    backgroundStyle: "gradient",
    featured: false,
    status: "published",
    createdBy: "usr_admin",
    isActive: true,
    createdAt: "2026-07-15T11:20:00Z"
  }
];

export const initialBookings = [
  {
    _id: "bk_101",
    user: { _id: "usr_demo", name: "Demo User", email: "demo@bookora.com" },
    event: initialEvents[0],
    quantity: 2,
    totalAmount: 4998,
    bookingStatus: "confirmed",
    paymentStatus: "paid",
    createdAt: "2026-07-20T14:22:00Z"
  },
  {
    _id: "bk_102",
    user: { _id: "usr_demo", name: "Demo User", email: "demo@bookora.com" },
    event: initialEvents[1],
    quantity: 1,
    totalAmount: 4999,
    bookingStatus: "confirmed",
    paymentStatus: "paid",
    createdAt: "2026-07-25T09:15:00Z"
  }
];
